In [26]:
import torch
import torch.nn as nn
import torch.optim as optim

In [27]:
# 1. Define a simple model and optimizer
model = nn.Linear(2, 1) # A linear model
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [33]:
# 2. Simulate a training step with a single data point
inputs = torch.randn(1, 2)
labels = torch.randn(1, 1)

In [34]:
inputs, labels

(tensor([[ 0.6041, -1.3248]]), tensor([[0.5254]]))

In [35]:
# ----- Training loop steps -----
optimizer.zero_grad()
outputs = model(inputs)
loss = (outputs - labels)**2
loss.backward() # Calculates gradients and stores in model.parameters().grad


In [40]:
outputs, loss

(tensor([[1.0452]], grad_fn=<AddmmBackward0>),
 tensor([[0.2702]], grad_fn=<PowBackward0>))

In [36]:
# Inspect gradients (for demonstration)
print("Gradient of weight:", model.weight.grad)
print("Gradient of bias:", model.bias.grad)

optimizer.step() # Updates parameters using the calculated gradients

Gradient of weight: tensor([[ 0.6280, -1.3773]])
Gradient of bias: tensor([1.0396])
