In [4]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

testset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=False, transform=transforms.ToTensor())

100%|██████████| 9.91M/9.91M [00:00<00:00, 22.3MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 600kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 5.56MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.49MB/s]


In [5]:
from torch.utils.data import DataLoader
testloader = DataLoader(testset, batch_size=64, shuffle=True)

In [6]:
testloader.dataset.data.shape

torch.Size([10000, 28, 28])

In [7]:
import torch
x = torch.randn(10)

In [8]:
print(x)

tensor([-1.9005,  0.9279,  0.6190, -0.4538,  0.9982, -1.2954,  0.6069, -0.2202,
         0.1777, -1.1444])


In [9]:
x.size()

torch.Size([10])

In [10]:
torch.randn(2,3)

tensor([[ 0.6280, -0.6072, -0.4851],
        [-0.7409, -0.7862, -0.0100]])

In [11]:
torch.randn(2,3,6)

tensor([[[ 0.3637, -2.4660,  0.1267, -0.4818, -0.4345, -0.7185],
         [-0.5043,  0.6200,  0.5161,  1.0713,  0.8788, -1.0329],
         [-0.3079,  0.3842, -0.4886, -0.9112,  1.3010, -0.0992]],

        [[-0.3590, -0.4897,  0.4549,  0.9207, -0.8461,  0.0180],
         [-0.8415,  0.9573,  1.0095,  0.6062,  0.9817, -0.8593],
         [-0.1513, -0.4257, -0.3424,  0.4791, -0.2536, -0.2716]]])

In [12]:
from torch.nn import Sigmoid
sigfunc = Sigmoid()
sigfunc(torch.tensor(2))

tensor(0.8808)