In [ ]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

testset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=False, transform=transforms.ToTensor())

100%|██████████| 9.91M/9.91M [00:00<00:00, 34.5MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.04MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 9.41MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 4.10MB/s]


In [ ]:
from torch.utils.data import DataLoader
testloader = DataLoader(testset, batch_size=64, shuffle=True)

In [ ]:
testloader.dataset.data.shape

torch.Size([10000, 28, 28])

In [ ]:
import torch
x = torch.randn(10)

In [ ]:
print(x)

tensor([-0.1907, -0.5722,  2.0931,  1.3636,  0.1599, -0.0776,  0.4942, -1.9817,
         1.6852, -0.1224])


In [ ]:
x.size()

torch.Size([10])

In [ ]:
torch.randn(2,3)

tensor([[-0.3128,  0.4853, -1.1611],
        [ 0.1597, -0.6119,  0.0082]])

In [ ]:
torch.randn(2,3,6)

tensor([[[-0.5788,  0.3518, -0.4606, -0.5885, -1.3621,  1.8769],
         [-1.2784, -0.5508, -1.1130,  0.3104,  0.4404,  2.5904],
         [ 0.9607, -1.0463, -0.8386,  0.1487,  1.5548,  0.3787]],

        [[ 2.5676, -1.5301, -1.0589, -0.3735,  0.2252, -2.9920],
         [-1.0518, -0.6477,  1.3738,  0.9628,  1.8223, -0.8502],
         [-0.5756,  0.7414,  1.0460, -1.1219,  1.0182,  0.5987]]])

In [1]:
from torch.nn import Sigmoid
sigfunc = Sigmoid()
sigfunc(2)

NameError: name 'Sigmoid' is not defined